### ISSUE TITLE
Cannot define tags from the "Build" dialog

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#565] opened 2016-03-24 06:57 UTC

**Comment by rbf** [comment] 2016-04-14 16:04
This is not a bug, but an enhancement. Do we want to implement tags also for builds? Flagging it as `✖︎ Outdated - Flagged for deletion` for discussion.

**Comment by rbf** [comment] 2016-04-20 12:06
Discussed with @loomis. There is no need for builds to have tags, since it's rather a one-shot action, and the run does not stay after the build is terminated. Closing issue.

**Closed by rbf** 2016-04-20 12:06 UTC
Labels: S04 Proposed for Sprint, T3 Enhancement, T5 Bug, ✖︎ Outdated - Flagged for deletion
