### ISSUE TITLE
Dashboard: Provide direct link from the usage gages to the corresponding subsection on 'Virtual Machines'

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#251] opened 2015-03-29 09:33 UTC

**Comment by rbf** [comment] 2015-06-03 05:05
Duplicate of #305, although the section suggested to be shown here is "Virtual machines" and in #305 is "Deployments".
Closing this issue.

**Closed by rbf** 2015-06-03 05:05 UTC
Labels: 0.5, S00 Backlog, T3 Enhancement, ★★
