### ISSUE TITLE
Can't change the category of parameters

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#152] opened 2014-09-08 15:27 UTC
If a parameter has an Input category value, changing it to Output is ignored.

A workaround is to deleted the parameter -> save -> edit and add it back with the right category

**Comment by rbf** [comment] 2015-02-17 15:54
@mebster 
The issue is still relevant, but it should be amended in the server side in order to take into account the change. The UI merely already allows it.

**Comment by rbf** [comment] 2015-05-19 14:37
Closing since it's a duplicate of #278.

**Closed by rbf** 2015-05-19 14:37 UTC
Labels: duplicate, pre v2.4, S00 Backlog, T5 Bug, ★★
