### ISSUE TITLE
running an image with input parameters fails

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#199] opened 2015-02-26 14:19 UTC
This feature is broken for images with input parameters. The Run... dialog should show input parameters without a default for the user to fill. Otherwise, the execute script will block and timeout.

**Comment by rbf** [comment] 2015-02-26 15:41
Is this not rather a bug than an enhancement?

**Comment by mebster** [comment] 2015-02-26 16:20
Indeed

**Comment by schaubl** [comment] 2015-03-18 17:04
Duplicate of #233.

**Closed by schaubl** 2015-03-18 17:04 UTC
Labels: duplicate, T5 Bug, ★★
