### ISSUE TITLE
unhelpful error message when image contains invalid script 

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#158] opened 2014-09-17 16:31 UTC
When the user provides an invalid deployment script (and probably also other types of scripts), the error message is just "[Errno 8] Exec format error".  This does not help the user determine which script has the problem and how to correct it.

For the screenshot, the problem was that the deployment script was lacking the she-bang line: `/bin/bash -x`.

![insufficient-error-message](https://cloud.githubusercontent.com/assets/490506/4307259/02c6aa58-3e88-11e4-9bfd-e17ce312bf88.png)

**Comment by rbf** [comment] 2015-02-17 15:50
@loomis I'm not able to reproduce this.
Anyway, if the problem is still relevant, it should be amended in the server side, providing a useful error message. The UI merely displays the `ss:abort` message.
Thus closing issue. Please re-open if you disagree.

**Closed by rbf** 2015-02-17 15:50 UTC
Labels: bug, pre v2.4, S00 Backlog
