### ISSUE TITLE
The feature which check if a Cloud is not configured doesn't work properly

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#311] opened 2015-05-17 23:49 UTC
I have credentials for all Clouds but most of them are considered not configured.
![cloud-not-configured](https://cloud.githubusercontent.com/assets/2462866/7672786/cee4ee34-fcff-11e4-9eeb-7a291b0de27b.png)
It seems to be related that for these Cloud the `Number of VMs the user can start for this cloud` is empty.
This bug is a blocking point for the release.

**Comment by rbf** [comment] 2015-05-18 12:03
I had a look at this issue. The cause is was @schaubl states: as of now the clouds considered _configured_ must have all fields non-blank, including the quota and other possible fields. There is no coherent way to determine which are the credentials pair because (as far as I have seen) all connector parameters (including the quota) are `mandatory="true"`.

If the quota is not mandatory to have a cloud properly configured, it should be `mandatory="false"`.

Currently a work-around is to provide a value for all fields in each connector.

@slipstream/owners Opinions?

**Comment by sixsq-hudson** [comment] 2015-05-18 12:09
In the case of quota, the default value should come from the system configuration.  Therefore, the value should either be filled in the user profil with that value by default, or we set it to not mandatory and the system will enforce it.  From a user point of view, it is important that they can see the read only quota value with the value assigned to them (20 by default).

Hope this helps.

**Comment by schaubl** [comment] 2015-05-18 13:19
@rbf : I think to correct way to do it (for now) is to check:
```
(username && password) || (access.id && secret.key)
```
As far as I know, it will work for all connectors.

Later on we can implement a better solution in SlipStreamServer.

**Closed** 2015-05-18 16:18 UTC
Labels: T5 Bug, ★★★
