### ISSUE TITLE
Link from registration email should fill user name in login page

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#215] opened 2015-03-03 09:15 UTC

**Comment by schaubl** [comment] 2015-03-07 14:43
Do you mean "last name" and "first name" ? 
If yes I would suggest to fill "Organization" as well.

**Comment by rbf** [comment] 2015-03-09 08:07
If I understood it right, this is not needed anymore, since the link from the registration email will bring the user to a page to only provide a login password, and once confirmed, the user will directly be logged in. So in my understanding, there is no need to fill the username in the login page.

**Comment by rbf** [comment] 2016-04-14 15:26
Related to https://github.com/slipstream/SlipStreamUI/issues/190.

**Comment by rbf** [comment] 2016-04-20 11:57
Discussed with @loomis. This issue is outdated. Closing issue.

**Closed by rbf** 2016-04-20 11:57 UTC
Labels: S00 Backlog, ✖︎ Outdated - Flagged for deletion
