### ISSUE TITLE
Run... Dialog replaces email parameter value with non-email value

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#495] opened 2015-12-01 18:49 UTC
See Drupal from App Store for example

**Comment by rbf** [comment] 2016-04-14 16:21
I cannot reproduce this bug:

![screen shot 2016-04-14 at 18 20 04](https://cloud.githubusercontent.com/assets/807084/14535327/9cf27f12-026d-11e6-9885-5d84f30e982a.png)

Closing issue.

**Closed by rbf** 2016-04-14 16:21 UTC
Labels: S04 Proposed for Sprint, T5 Bug
